# Generated by Django 6.0.5 on 2026-05-21 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receitapublica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receitapublica',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='receitas_publicas_favoritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receita',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='receitapublica',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='AvaliacaoPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_publicas', to='receitas.receitapublica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('receita', 'usuario')},
            },
        ),
    ]
