# Generated by Django 6.0.5 on 2026-05-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receitapublica_favoritos_alter_grupofamiliar_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitapublica',
            name='privada',
            field=models.BooleanField(default=False),
        ),
    ]
