from django.urls import path
from . import views

urlpatterns = [
    path('', views.feed, name='home_redirect'),
    path('grupos/', views.home, name='home'),
    path('registrar/', views.registrar, name='registrar'),
    path('login/', views.fazer_login, name='login'),
    path('logout/', views.fazer_logout, name='logout'),
    path('grupo/criar/', views.criar_grupo, name='criar_grupo'),
    path('grupo/<int:pk>/', views.detalhe_grupo, name='detalhe_grupo'),
    path('grupo/<int:grupo_pk>/sair/', views.sair_grupo, name='sair_grupo'),
    path('grupo/<int:pk>/excluir/', views.excluir_grupo, name='excluir_grupo'),
    path('grupo/<int:grupo_pk>/transferir-admin/', views.transferir_admin, name='transferir_admin'),
    path('grupo/<int:grupo_pk>/receita/adicionar/', views.adicionar_receita, name='adicionar_receita'),
    path('receita/<int:pk>/favoritar/', views.favoritar_receita, name='favoritar_receita'),
    path('receita/<int:pk>/remover/', views.remover_receita, name='remover_receita'),
    path('receita/<int:pk>/', views.detalhe_receita, name='detalhe_receita'),
    path('receita/<int:pk>/avaliar/', views.avaliar_receita, name='avaliar_receita'),
    path('avaliacao/<int:pk>/remover/', views.remover_avaliacao, name='remover_avaliacao'),
    path('feed/', views.feed, name='feed'),
    path('feed/publicar/', views.publicar_receita_publica, name='publicar_receita_publica'),
    path('feed/receita/<int:pk>/remover/', views.remover_receita_publica, name='remover_receita_publica'),
    path('feed/receita/<int:pk>/', views.detalhe_receita_publica, name='detalhe_receita_publica'),
    path('feed/receita/<int:pk>/avaliar/', views.avaliar_receita_publica, name='avaliar_receita_publica'),
    path('feed/receita/<int:pk>/favoritar/', views.favoritar_receita_publica, name='favoritar_receita_publica'),
    path('feed/avaliacao/<int:pk>/remover/', views.remover_avaliacao_publica, name='remover_avaliacao_publica'),
    path('favoritas/', views.receitas_favoritas, name='receitas_favoritas'),
    path('minhas-receitas-privadas/', views.minhas_receitas_privadas, name='minhas_receitas_privadas'),
    path('feed/receita/<int:pk>/tornar-publica/', views.tornar_publica, name='tornar_publica'),
    path('feed/receita/<int:pk>/tornar-privada/', views.tornar_privada, name='tornar_privada'),
    path('grupo/<int:grupo_pk>/convidar/', views.convidar_membro, name='convidar_membro'),
    path('convite/<int:convite_pk>/aceitar/', views.aceitar_convite, name='aceitar_convite'),
    path('convite/<int:convite_pk>/recusar/', views.recusar_convite, name='recusar_convite'),
]